#!/bin/sh
#
# Sign the unsigned APK generated by build-android.sh
#
# Environment variables used by this script:
#
# - ANDROID_KEYSTORE:
#   Path to the Android keystore file (.jks).
#
# - ANDROID_KEYSTORE_PASSWORD:
#   Password for the keystore.
#
# - ANDROID_KEY_PASSWORD:
#   Password for the key entry inside the keystore.
#
# - ANDROID_KEY_ALIAS:
#   Alias of the key inside the keystore.
#
# These variables may be exported in the environment before running the
# script to sign a release or debug APK.
# If the required variables are not set, the script will generate a temporary debug keystore and key.
# This debug key is suitable for sideloading the APK on devices.
#

set -e

basedir="$(realpath "$0" | xargs dirname)"
. "$basedir/scripts/lib.sh"

APK_UNSIGNED="letmein-aarch64-unsigned.apk"
APK_SIGNED="letmein-aarch64.apk"
AAB_UNSIGNED="letmein-aarch64.aab"
AAB_SIGNED="letmein-aarch64-signed.aab"

cd "$basedir"

if ! [ -r "$APK_UNSIGNED" ]; then
    die "Error: unsigned APK not found at $APK_UNSIGNED. Please run build-android.sh first."
fi
if ! [ -r "$AAB_UNSIGNED" ]; then
    die "Error: unsigned AAB not found at $AAB_UNSIGNED. Please run build-android.sh first."
fi
if [ -z "$ANDROID_KEYSTORE" ]; then
    ANDROID_KEYSTORE="$basedir/debug.jks"
    ANDROID_KEYSTORE_PASSWORD=android
    ANDROID_KEY_PASSWORD=android
    ANDROID_KEY_ALIAS=debug-key
    if ! [ -r "$ANDROID_KEYSTORE" ]; then
        keytool \
            -genkeypair \
            -v \
            -keystore "$ANDROID_KEYSTORE" \
            -alias "$ANDROID_KEY_ALIAS" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "$ANDROID_KEYSTORE_PASSWORD" \
            -keypass "$ANDROID_KEY_PASSWORD" \
            -dname "CN=Debug, O=Debug, C=US"
    fi
fi
if ! [ -r "$ANDROID_KEYSTORE" ]; then
    die "Error: Android keystore not found at $ANDROID_KEYSTORE"
fi
if [ -z "$ANDROID_KEY_ALIAS" ]; then
    die "Error: ANDROID_KEY_ALIAS environment variable not set"
fi
if [ -z "$ANDROID_KEYSTORE_PASSWORD" ]; then
    die "Error: ANDROID_KEYSTORE_PASSWORD environment variable not set"
fi
if [ -z "$ANDROID_KEY_PASSWORD" ]; then
    die "Error: ANDROID_KEY_PASSWORD environment variable not set"
fi

apksigner \
    sign \
    --ks "$ANDROID_KEYSTORE" \
    --ks-key-alias "$ANDROID_KEY_ALIAS" \
    --ks-pass pass:"$ANDROID_KEYSTORE_PASSWORD" \
    --key-pass pass:"$ANDROID_KEY_PASSWORD" \
    --out "$APK_SIGNED" \
    "$APK_UNSIGNED"

jarsigner \
    -verbose \
    -sigalg SHA256withRSA \
    -digestalg SHA-256 \
    -keystore "$ANDROID_KEYSTORE" \
    -storepass "$ANDROID_KEYSTORE_PASSWORD" \
    -keypass "$ANDROID_KEY_PASSWORD" \
    -signedjar "$AAB_SIGNED" \
    "$AAB_UNSIGNED" \
    "$ANDROID_KEY_ALIAS"
